use_frameworks!

target 'GTMotionInterchange_Example' do
  pod 'GTMotionInterchange', :path => '../'

  target 'GTMotionInterchange_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
